# Generated by Django 4.0.3 on 2022-03-16 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_member_delete_itemsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
    ]
