# Generated by Django 4.0.3 on 2022-03-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_autor_libro_delete_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autores',
        ),
    ]
